FROM registry.cn-beijing.aliyuncs.com/dkzx_test/algorithm_base_image:prefect_3.4.14

WORKDIR /app
COPY . /app/

ENV PYTHONPATH=/app
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements_algorithm_image_tree.txt
