FROM python:3.10.18

WORKDIR /app
COPY requirements_algorithm_general_image.txt /app/

RUN apt update && \
    apt install -y --no-install-recommends \
        git \
        build-essential \
        cmake \
        g++ \
        libgomp1 \
        wget \
        vim \
        libffi-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip install --no-cache-dir --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --no-cache-dir torch torchvision && \
    pip install --no-cache-dir tabpfn && \
    pip install --no-cache-dir -r requirements_algorithm_general_image.txt && \
    rm -rf /root/.cache/pip /tmp/*
