FROM algorithm_base_image:prefect_3.4.14

WORKDIR /app
COPY . /app/

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

ENV PREFECT_API_URL="https://admin:ajiotadmin@prefect.ajiot.net:58443/api"
RUN pip install pyexecjs==1.5.1

ENV POOL_NAME=""

#CMD sh -c "prefect worker start --pool \"$POOL_NAME\""
#ENTRYPOINT ["prefect", "worker", "start", "--pool"]
CMD ["sh","-c",  "prefect worker start --pool $POOL_NAME"]