FROM registry.cn-beijing.aliyuncs.com/dkzx_test/algorithm_base_image:prefect_3.4.14_tf_2.20.0-gpu

WORKDIR /app
COPY . /app/

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

ENV PREFECT_API_URL="https://admin:ajiotadmin@prefect.ajiot.net:58443/api"

ENV POOL_NAME=""

CMD ["sh","-c",  "prefect worker start --pool $POOL_NAME"]